# Generated by Django 5.1.4 on 2024-12-27 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('data_alterado', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema.', verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsável')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('usuario_adiciona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alterado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Alterou')),
            ],
            options={
                'verbose_name': 'Centro de Distribuição',
                'verbose_name_plural': 'Centros de Distribuição',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('data_alterado', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema.', verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario_adiciona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alterado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Alterou')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('data_alterado', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema.', verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario_adiciona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alterado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Alterou')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('data_alterado', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema.', verbose_name='Ativo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estoque_minimo', models.PositiveIntegerField(verbose_name='Estoque Mínimo')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário')),
                ('unidade_medida', models.CharField(max_length=10, verbose_name='Unidade de Medida')),
                ('usuario_adiciona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alterado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Alterou')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição')),
                ('data_alterado', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o registro está ativo no sistema.', verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('usuario_adiciona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Adicionou')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_alterado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Alterou')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
